[tool.black]
line-length = 120
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
select = ["ALL"]
extend-ignore = ["E501", "ANN201", "ANN001", "D" ]
fix = true
line-length = 120

[tool.ruff.per-file-ignores]
"tests/*.py" = ["S101", "D103"]
