name: Check Jira key in PR title exists and is valid
# Runs when opening or changing a PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, edited]
    branches:
      - main
jobs:
  # This workflow contains a single job called "check-jira"
  check-jira:
    # Run on Ubuntu (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./branch
        if: startsWith( github.ref, 'refs/heads/release') == false
        with:
          valid-branch-names: task|test|bugfix|feature|hotfix|epic
          jira-username: automation@arup.com
          jira-password: ${{ secrets.JIRA_PASSWORD }}
          branch_to_check: refs/heads/${{ github.event.pull_request.head.ref }}
          pr_title: ${{ github.event.pull_request.title }}
